name: frontend
description: A new Flutter project.
publish_to: 'none'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5



version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true


